### ISSUE TITLE
NativeSocket's read() cannot read more all the bytes we want at once

### ISSUE THREAD

**Issue by SlNPacifist** [pheanstalk/pheanstalk#16]
I've encountered this problem on Windows XP, php 5.2.10 - jobs sized more than 4096 bytes and less than 8192 (due to previous bug fix) cannot be read - exception "Pheanstalk_Exception_ClientException: Expected 2 bytes of CRLF after 5000 bytes of data" is throwed.
I get this problem randomly on Debian Lenny, php 5.2.6 - exception is throwed really randomly, but always with job size less than 8192 bytes.

I've forked pheanstalk into http://github.com/SlNPacifist/pheanstalk, wrote a test for this bug (trying to put, peek and delete jobs with size incrementing from 1000 to 16000 with step 1000) (will commit soon).
Expecting getting rid of "read-at-once" optimisation to be the solution.

**Comment by shreyashib** [comment]
Hi

I had issue with server hence i restarted the server.
But from the time i am reciving this error Expected 2 bytes of CRLF after 26787 bytes of data
Pheanstalk.php(533): Pheanstalk_Connection->dispatchCommand(Object(Pheanstalk_Command_ReserveCommand))
I have restarted the Beanstalkd and the instance of worker process.
But still the issue. 
I am using 
Beanstalkd V1.4.6
Pheanstalk V2.0.0
