### ISSUE TITLE
Configure Scrutinizer CI

### ISSUE THREAD

**Issue by SamMousa** [pheanstalk/pheanstalk#172]
I'd like to integrate Scrutinizer CI get some feedback on code quality and code coverage.

This requires admin access to the repository.
@pda Could you set up the basic integration on scrutinizer-ci.com? 

After you've done that I should be able to create the configuration with my current permissions.

**Comment by pda** [comment]
@SamMousa it seems like you've been doing an epic job. Do you think we should transfer ownership of the GitHub repo to you?

https://help.github.com/articles/about-repository-transfers/

**Comment by pda** [comment]
(I only just found this issue because I decided to search `in:inbox pheanstalk "@pda"` in my email, but I can't guarantee to do that often/ever. I'd hate to be the blocker on great progress.)

**Comment by SamMousa** [comment]
I suggest creating an organisation instead!

**Comment by pda** [comment]
Oh yeah — if you create the org, I'll transfer the repo.

**Comment by SamMousa** [comment]
https://github.com/pheanstalk 

Done!

**Comment by pda** [comment]
… and done!
