### ISSUE TITLE
StreamSocket doesn't write to stream and gets stuck in infinite loop

### ISSUE THREAD

**Issue by aripringle** [pheanstalk/pheanstalk#184]
When testing the master branch (9e2fe0006254ee1706bd9e6c19d19f3efe9922eb) for some changes in #180, I wasn't successfully able to use the StreamSocket implementation (which was used as the default implementation when the `sockets` extension isn't loaded).

It seems that this line:
```
$written = @fwrite($this->socket, $data);
```

Is always returning `0`, even though `$data` has a value. I've tried to debug the code, and haven't been able to find any errors that indicate why (I removed the `@` preceding fwrite, verified that `error_get_last()` is null, and verified that the $error and $errorMessage values set by `stream_socket_client()` are empty).

This ends up causing an infinite loop. I've also confirmed that the beanstalk server isn't receiving the command (`$data` in this case is `watch testtube`, and I can see that there are no connections to that tube on the server).

The same exact implementation code works fine just by enabling the sockets PHP extension (thus causing it to use SocketSocket).

Let me know if there's anything else I can look at to help debug this.

**Comment by SamMousa** [comment]
Thanks, I still have to update the test suite to test all backends. Will do that tomorrow.

**Comment by SamMousa** [comment]
I think I've fixed the issue. The tests now use all socket implementations.

We should still create separate tests for the socket implementations that mock the underlying functions to test behaviors that are hard to replicate.

**Comment by aripringle** [comment]
Thanks, StreamSocket seems to work fine with the latest commit to master. As with the latest 3.x release, if a `reserve` command runs long enough, it will eventually timeout and throw a `SocketException` (now with an "Unknown error" message) that would have to be caught and handled in the userland code.
