### ISSUE TITLE
Infinite job TTR

### ISSUE THREAD

**Issue by grabowskimfs** [pheanstalk/pheanstalk#185]
Is there any way to set infinite TTR  on a job ?
I have multiple workers watching the same tube and also some of my jobs can take more than 1 min (don't know exactly how long).

**Comment by SamMousa** [comment]
Infinity is not an integer, but you could set it to a large value to get what you need.

A better solution is to touch the job during execution; so set ttr to the longest step in you job (+ some margin) and touch it after each step.

Downside of long ttr is that a crashed worker will cause jobs to stay reserved for a long time.
