### ISSUE TITLE
it can't consume job when the tube is empty for a while

### ISSUE THREAD

**Issue by twn39** [pheanstalk/pheanstalk#189]
I write a loop to reserve the job, it work fine. But a period of time later, it cant't comsume the job, 
I see the job is ready through beanstalk console. When I restart the php script, it consume the job again.
I don't know why, can someone help me ?

enviroment:
php: 7.0.33
pheanstalk: 3.1.0

**Comment by SamMousa** [comment]
This is a connection issue that is hard to detect. Could you try v4?

**Comment by twn39** [comment]
I think this is beastalkd issue, it has this problem when i use telnet. When the tube keep **empty** for a while maybe 2 or 3 hours, It will never consume the new job. So I set timeout when reserve and then reconnect.

**Comment by SamMousa** [comment]
It's not, it's a network issue. V4 uses TCP keepalive so it will detect broken connections.

**Comment by twn39** [comment]
I will try v4, thanks
