### ISSUE TITLE
PHP 7.1 or PHP 7.2 minimum requirement?

### ISSUE THREAD

**Issue by alanhartless** [pheanstalk/pheanstalk#191]
Hi!

In the readme it says 7.2+ but in composer.json, PHP has a minimum requirement of 7.1. Which is it really? 

Thanks!
Alan

**Comment by SamMousa** [comment]
Hmm, tests seem to run on 7.1 on Travis, so 7.1 it is. I'll double check on a PC tomorrow and will update the readme! Thanks.

**Comment by SamMousa** [comment]
It's 7.1, thanks for pointing out the mistake in the docs.

**Comment by alanhartless** [comment]
Thanks! That's good news for us :-D
