### ISSUE TITLE
Ignore default not working properly

### ISSUE THREAD

**Issue by alvarocabanas** [pheanstalk/pheanstalk#194]
Hello and thanks for your help.

We have a monolith application that is writing jobs in the default tube of beanstalk. Then we have a microservice that writes and reads in another tube called 'user_notifications'. We specifically tell pheanstalk to ignore 'default' but the reserve call is getting jobs from 'default'.

I've tried getting listTubesWatched and it only appears 'user_notifications', but if the reserve() gets a job and I call listTubeUsed() I get 'default'.

This is the code we are using having the workaround to release unwanted jobs, but I think this is not working how it should, or maybe we are doing something wrong:

        ```
        $this->pheanstalk->watch('user_notifications');
        $this->pheanstalk->ignore('default');

        $this->job = $this->pheanstalk->reserve();

        if ($this->pheanstalk->listTubeUsed() != 'user_notifications') {
            $this->pheanstalk->release($this->job);
            throw new WrongQueueException('Job released');
        }

        $this->handleJob($this->job->getData());
```

Can you help us?

**Comment by SamMousa** [comment]
This is not an issue in this library.
Please check the Beanstalk protocol specification or the documentation. There is a difference between watched tubes (reading) and used tube (writing); I suspect this is the cause of your issue.

**Comment by gdsmith** [comment]
Recently upgraded a monolith to v4 and came across a similar problem.

Whilst the code above is mistaking the use and watch, it looks like there is a bug in v4 where it will _always_ watch the default tube if there is any kind of reconnection.

If I make reconnect public then the following code illustrates the issue:

```php
$pheanstalk = Pheanstalk::create('beanstalkd');
$pheanstalk->watchOnly('test');
var_dump($pheanstalk->listTubesWatched(TRUE));
$pheanstalk->reconnect();
var_dump($pheanstalk->listTubesWatched(TRUE));
```

That will output:

```
array (size=1)
  0 => string 'test' (length=4)
array (size=1)

array (size=2)
  0 => string 'default' (length=7)
  1 => string 'test' (length=4)
```
