### ISSUE TITLE
Get current tube with multiple watches

### ISSUE THREAD

**Issue by cherimo** [pheanstalk/pheanstalk#197]
Hey there,

I am using multiple watches like this:
$job = $pheanstalk->watch('failled-order')->watch('success-order')->ignore('default')->reserve();

Is it possible to detect which tube the worker is processing at the moment? At this moment I have put the data tubename in the array to detect which tube is now being processed.

**Comment by alister** [comment]
There is a `statsJob()` pheanstalk call that will return data given the $job.

**Comment by SamMousa** [comment]
> Is it possible to detect which tube the worker is processing at the moment?

I assume you mean detecting which tube the job came from?
As @alister mentioned you could use `statsJob()` for that. Though in my opinion all information a task runner needs should be contained in the task. Which tube it came in through shouldn't really matter.
