### ISSUE TITLE
Migrating from v3 to v4

### ISSUE THREAD

**Issue by sashabeton** [pheanstalk/pheanstalk#201]
Can you please create a changelog for v4 or explain all breaking changes? What does `persistent connection` mean and how it worked? What functions have been deleted and which functions had side effect?

**Comment by SamMousa** [comment]
Yes I can!

**Comment by sashabeton** [comment]
Thank you very much!

пт, 2 авг. 2019 г. в 11:01, Sam <notifications@github.com>:

**Comment by SamMousa** [comment]
@sashabeton let me know if you have any specific questions that need answering.
