### ISSUE TITLE
peekBuried return null   

### ISSUE THREAD

**Issue by mahaidongs** [pheanstalk/pheanstalk#204]
My code :

\require_cache(VENDOR_PATH.'vendor/autoload.php');
        $pheanstalk = Pheanstalk::create('172.17.159.124');
        print_r($pheanstalk->statsTube('arts')); 
        $job = $pheanstalk->peekBuried();  var_dump($job );

print:
       

> 
Pheanstalk\Response\ArrayResponse Object
(
    [name:Pheanstalk\Response\ArrayResponse:private] => OK
    [storage:ArrayObject:private] => Array
        (
            [name] => arts
            [current-jobs-urgent] => 0
            **[current-jobs-ready] => 7**
            [current-jobs-reserved] => 0
            [current-jobs-delayed] => 0
            [current-jobs-buried] => 0
            [total-jobs] => 7
            [current-using] => 0
            [current-watching] => 0
            [current-waiting] => 0
            [cmd-delete] => 0
            [cmd-pause-tube] => 0
            [pause] => 0
            [pause-time-left] => 0
        )

)
**NULL**

**Comment by alister** [comment]
>   [current-jobs-ready] => 1
>   [current-jobs-buried] => 0

You don't have any buried jobs, at least, not in that tube.

```
$pheanstalk->useTube('arts')->put("job in arts");
//print_r($pheanstalk->statsTube('arts'));

$job = $pheanstalk->peekBuried(); 
var_dump(['peekBuried' => $job]);
// array(1) {
//   ["peekBuried"]=>
//   NULL
// }

$job = $pheanstalk->peekReady(); 
print_r($job);
// Pheanstalk\Job Object
// (
//     [id:Pheanstalk\Job:private] => 26
//     [data:Pheanstalk\Job:private] => job in arts
// )
```

**Comment by mahaidongs** [comment]
tks

**Comment by mahaidongs** [comment]
> > [current-jobs-ready] => 1
> > [current-jobs-buried] => 0
> 
> You don't have any buried jobs, at least, not in that tube.
> 
> ```
> $pheanstalk->useTube('arts')->put("job in arts");
> //print_r($pheanstalk->statsTube('arts'));
> 
> $job = $pheanstalk->peekBuried(); 
> var_dump(['peekBuried' => $job]);
> // array(1) {
> //   ["peekBuried"]=>
> //   NULL
> // }
> 
> $job = $pheanstalk->peekReady(); 
> print_r($job);
> // Pheanstalk\Job Object
> // (
> //     [id:Pheanstalk\Job:private] => 26
> //     [data:Pheanstalk\Job:private] => job in arts
> // )
> ```

tks

**Comment by SamMousa** [comment]
Sorry for my slow response; apparently I was not watching this repo and therefore not receiving notifications.

I'm gonna go ahead and close this. @alister thanks for the assist!
