### ISSUE TITLE
socket_set_option

### ISSUE THREAD

**Issue by panicoschr** [pheanstalk/pheanstalk#205]
Hi. I am using laravel and beanstalkd. Before  jobs dispatched and worked. Now i received exception error below. 
After searching i found something and i replaced the vendor\pda\pheanstalk\src\Socket\SocketSocket.php:39       
 socket_set_option($this->socket, **SOL_TCP**, SO_KEEPALIVE, 1);  to
 socket_set_option($this->socket, **SOL_SOCKET**, SO_KEEPALIVE, 1); 
and it works. Why is this happening. I ma not sure if it is related but i was working on creating a php websocket connection between xampp and my view (client). I dispatched this connection creation as a job. Is it possible something was/to be alive and causing this error exception? Thank you.

 ErrorException  : socket_set_option(): unable to set socket option [10042]: An unknown, invalid, or unsupported option or level was specified in a getsockopt or setsockopt call.
  at C:\xampp\htdocs\myproject\myproject\vendor\pda\pheanstalk\src\Socket\SocketSocket.php:39

    37|         $sendTimeout = socket_get_option($this->socket, SOL_SOCKET, SO_SNDTIMEO);
    38|         $receiveTimeout = socket_get_option($this->socket, SOL_SOCKET, SO_RCVTIMEO);
    39|         socket_set_option($this->socket, SOL_TCP, SO_KEEPALIVE, 1);
    40|         socket_set_option($this->socket, SOL_SOCKET, SO_SNDTIMEO, $timeout);
    41|         socket_set_option($this->socket, SOL_SOCKET, SO_RCVTIMEO, $timeout);
    42|         socket_set_block($this->socket);

  Exception trace:
  1   socket_set_option()
      C:\xampp\htdocs\myproject\myproject\vendor\pda\pheanstalk\src\Socket\SocketSocket.php:39
  2   Pheanstalk\Socket\SocketSocket::__construct("beanstalkedserver")
      C:\xampp\htdocs\myproject\myproject\vendor\pda\pheanstalk\src\SocketFactory.php:69

**Comment by SamMousa** [comment]
Strange, the line is covered by code coverage...

What PHP version are you using?

**Comment by panicoschr** [comment]
7.3.8

**Comment by SamMousa** [comment]
Hmm, are you on windows?

**Comment by panicoschr** [comment]
Yes, windows 10.

**Comment by SamMousa** [comment]
Thanks for the clear report!

- I have reproduced the issue on Windows
- Discovered that on linux, even though it does not throw an error it does not actually activate keep alive on the socket.

Are you up for making a PR with the above changes?

**Comment by panicoschr** [comment]
yes

**Comment by panicoschr** [comment]
This is my first Pull Request, just to let you know. Is it done correctly?

**Comment by SamMousa** [comment]
Yes, looks great!

For future reference: always reference the issue number in your PR, also describe what you have implemented in the discription.

In this case there's 1 issue and 1 pr so it's all good :)
