### ISSUE TITLE
Looking for documentation?

### ISSUE THREAD

**Issue by GregsGrog** [pheanstalk/pheanstalk#211]
Title pretty much sums it up, i've looked everywhere for docs and this was my last resort?

**Comment by SamMousa** [comment]
I've looked everywhere for a bug report or a question in your issue. Didn't find either.

**Comment by GregsGrog** [comment]
Ok so im assuming there isn't any then? I wasnt trying to be rude, im very sorry if I bothered you.

**Comment by SamMousa** [comment]
The documentation is in the README as far as it exists.
If you want to contribute more detailed documentation you are free to. I'll look into some automated doc generation from source code.
