### ISSUE TITLE
Feature Request: Throw specific exceptions

### ISSUE THREAD

**Issue by le-oliver** [pheanstalk/pheanstalk#217]
At the moment some exceptions just raises a default exception class (\Pheanstalk\Exception). Would be nice to have exception classes for all the different kinds of exceptions in order to be able to catch them more targeted to be able to handle them accordingly.

Example: 
\Pheanstalk\Command\PutCommand::parseResponse()
4 things can go wrong, but its always just \Pheanstalk\Exception

**Comment by SamMousa** [comment]
I agree, are you up for making a PR? This is a change that doesn't break backwards compatibility so we can get it in in a minor release

**Comment by le-oliver** [comment]
Sure, if it can wait a couple of days I can PR this.

**Comment by SamMousa** [comment]
Closed via #218
