### ISSUE TITLE
when I use beanstalk in Multiple processes get a responsed error

### ISSUE THREAD

**Issue by easytoeasy** [pheanstalk/pheanstalk#220]
Dear friends:
I'm just learning beanstalk, and then I meet a error  as follows:
```
string(12) "INSERTED 190"
/Users/pzr/myProject/public/yii2-amqp/vendor/pda/pheanstalk/src/Command/PutCommand.php:67:
string(12) "INSERTED 191"
/Users/pzr/myProject/public/yii2-amqp/vendor/pda/pheanstalk/src/Command/PutCommand.php:67:
INSERTED 193"SERTED 192
/Users/pzr/myProject/public/yii2-amqp/vendor/pda/pheanstalk/src/Command/PutCommand.php:67:
string(1) "N"
```
As you can see "INSERTED 193"SERTED 192" and "N" is not what excepted value, and obviously the returned string is out of whack.
I used socket connected and in multiple processes , I think maybe the beanstalk server response is't block , so the response string be cuted. 
If I want to use beanstalk in multiple processes How I to do? 
Hope get your answer and thanks :)

**Comment by easytoeasy** [comment]
Supplement: This error occurs when I write a multi-process job and start a consumer in a consuming job.

**Comment by easytoeasy** [comment]
I trace the code:
```php
$buffer = '';
        // Reading stops at \r or \n. In case it stopped at \r we must continue reading.
        while (substr($buffer, -1, 1) !== "\n") {
            //$result = socket_read($this->socket, 1024, PHP_BINARY_READ);
            $result = socket_read($this->socket, 1024, PHP_NORMAL_READ);
            // var_dump($result);
            if ($result === false) {
                $this->throwException();
            }
            $buffer .= $result;
        }
```
I wonder if \r\n was written in the wrong place because the contents read by PHP_NORMAL_READ were in multiple processes. It would have been better if I had read the contents using PHP_BINARY_READ, but there would still be another problem:
Pheanstalk\Exception: Unhandled response: Slipped 54
INSERTED 55 in XXX
You see that a line break appears between INSERTED 54 and INSERTED 55, It should also be caused by multi-process writing. Is there a better way to solve this problem?

**Comment by SamMousa** [comment]
I'm sorry but I can't make sense of this. Multiple processes shouldn't be relevant in anyway for beanstalk or for this library. What version are you using?

**Comment by easytoeasy** [comment]
> I'm sorry but I can't make sense of this. Multiple processes shouldn't be relevant in anyway for beanstalk or for this library. What version are you using?

v4.0.1, use composer installed .

**Comment by SamMousa** [comment]
I'm sorry @easytoeasy even after giving it another look I am unable to even understand what your issue is, let alone look at a solution.

**Comment by easytoeasy** [comment]
I tried to write a demo, but it didn't reproduce. I don't know what caused it. thanks a lot.

**Comment by easytoeasy** [comment]
It's been a long time, and today when I was writing a multi-process test, the same problem recurred, and I thought about this issue again. So I wrote a piece of code that looks like this:

```php
define('QUEUE', 'beanstalk');
require './vendor/autoload.php';
$talker = Pheanstalk::create('127.0.0.1');
for ($i = 0; $i < 10; $i++) {
    $pid = pcntl_fork();
    if ($pid < 0) {
        exit();
    } elseif ($pid > 0) {
    } else {
        $jobs = 'test';
        $talker->useTube(QUEUE)->put(json_encode($jobs));
    }
}
```
and then get result like this:
```
thrown in /xxx/vendor/pda/pheanstalk/src/Command/PutCommand.php on line 92
PHP Fatal error:  Uncaught Pheanstalk\Exception: Unhandled response: 1INSERTED 172 in /xxx/vendor/pda/pheanstalk/src/Command/PutCommand.php:92
```
Thank you for your patience and I look forward to your reply.

**Comment by SamMousa** [comment]
If you fork a process, I assume it shares the same sockets, that won't ever work, it is not a beanstalk or Pheanstalk issue. 

Connecting after the fork should work. What is weird though is that a socket gets created so early at all. 
Just having `Pheanstalk:create('127.0.0.1')` shouldn't connect.

Steps to further debug, make sure to include the correct classes, then use this to initialize.
```php
use Pheanstalk\SocketFactory;
$talker = Pheanstalk:createWithFactory(new class('127.0.0.1', 11300) extends SocketFactory {
    public function create(): SocketInterface 
    {
        echo "CREATING SOCKET\N"
        return parent::create();
    }
}
for ($i = 0; $i < 10; $i++) {
    echo "Starting fork $i\n";
    $pid = pcntl_fork();
    if ($pid < 0) {
        exit();
    } elseif ($pid > 0) {
    } else {
        echo "Putting from process $i\n"
        $jobs = 'test';
        $talker->useTube(QUEUE)->put(json_encode($jobs));
    }
}


```
Run something like this and provide the output and we'll see whether sockets are being created before forking happens.

**Comment by SamMousa** [comment]
@easytoeasy did you resolve your issue? If so please leave a comment for people who experience it in the future!
