### ISSUE TITLE
Support for reserve-job

### ISSUE THREAD

**Issue by scottmac** [pheanstalk/pheanstalk#221]
I started adding this but it's not clear what the best way to handle calling the command on pre-1.12 versions.

We're unable to actually catch BAD_FORMAT as it always throws an exception in the connection class.

**Comment by SamMousa** [comment]
Shouldn't the server return UNKNOWN_COMMAND?

**Comment by scottmac** [comment]
Patch so far, can put up as a PR if interested. https://gist.github.com/scottmac/87ee7dcad48fbd34ffd0611003af4996

```
echo -e "reserve-job 1\r\n" | nc localhost 11300
BAD_FORMAT
```

**Comment by SamMousa** [comment]
We should make a bug report upstream to see if this is actually a bug in beanstalkd.

Regarding your patch, please use the `JobIdInterface` as param instead of an int.

**Comment by scottmac** [comment]
Looks like beanstalkd does a sub-string match. If a command is a sub-string of an existing one it returns bad format rather than UNKNOWN_COMMAND.

```
scott@whisky-west:~/dev/pheanstalk$ echo -e "stats-a\r\n" | nc localhost 11300
BAD_FORMAT

scott@whisky-west:~/dev/pheanstalk$ echo -e "foo\r\n" | nc localhost 11300
UNKNOWN_COMMAND
```
