### ISSUE TITLE
Pheanstalk 5

### ISSUE THREAD

**Issue by SamMousa** [pheanstalk/pheanstalk#223]
Proposed changes for version 5.

- [ ] Explicitly exclude new functions in `PheanstalkInterface` from BC promise, we will however not change signatures.
- [x] Upgrade minimum PHP to 8.0
- [x] Add return type hints where possible
- [x] Add support for `reserve-job` (#222)
- [x] Move to github actions  (away from Travis)
- [x] Add a job for static analysis (PHPStan)
- [x] Add job for code style PSR12

Please add anything you'd like to see for v5 here.

**Comment by gopi-ar** [comment]
Do we already support UNIX sockets? If not, might be good to add to v4 and v5!

**Comment by SamMousa** [comment]
Can you make a PR?

**Comment by binaryfire** [comment]
Really looking forward to v5. Any idea on a release timeframe yet?

**Comment by SamMousa** [comment]
Not yet; I'd prefer to have some people run it first. I'm not using it in production yet myself, which is the minimum requirement for me to release it as a stable release.

**Comment by SamMousa** [comment]
@binaryfire are you using v5 currently?

**Comment by binaryfire** [comment]
@SamMousa Unfortunately not. We don’t have the resources for beta testing at the moment so we’re sticking with the latest stable release

**Comment by devudopw** [comment]
I can test v5 in my staging, any migration needed from v4 to v5?

**Comment by SamMousa** [comment]
Yes definitely. Should be documented in the Readme. Will post a link when at a pc.

**Comment by SamMousa** [comment]
https://github.com/pheanstalk/pheanstalk/pull/244 

Hmm, docs are still on the todo. If you're using static analysis you should be detect any incorrect usages, one of the points of v5 is to move towards strict typing which should automatically detect invalid calls to library code.

Please let me know how it goes and if you're up for keeping notes while transitioning they could form the basis for migration docs.

**Comment by danielbeardsley** [comment]
I'm transitioning ifixit.com to v5.x-dev right now, we'll see how it goes. It's not clear what's left to do for a real release.

**Comment by SamMousa** [comment]
I'll release it soon, not much needed iirc

**Comment by SamMousa** [comment]
@danielbeardsley I've just released `v5.0.0-rc.1` and after I've integrated that into our application in prod i'll tag it as a stable release.

**Comment by SamMousa** [comment]
> I can test v5 in my staging, any migration needed from v4 to v5?

@devudopw you should be able to run the latest RC now. For me migration was mostly limited to configuration of the DI container. If you use static analysis it will be able to detect any bad call sites automatically.

**Comment by devudopw** [comment]
> 

Appreciate your work!!
My use case does not includes much dependencies, it should be easy migration.
I will try v5 RC and report back.

**Comment by SamMousa** [comment]
Released!
