### ISSUE TITLE
Timeout is a float in fsockopen, wrongly set in Pheanstalk, Socket

### ISSUE THREAD

**Issue by beberlei** [pheanstalk/pheanstalk#225]
https://www.php.net/manual/en/function.fsockopen.php defines timeout as a float, however Pheanstalk defines it as an integer. That prevents setting it to values such as `0.1` or `0.2` to get sub-second connection timeouts on infrastructures where Beanstlak server is close to the application server.

**Comment by SamMousa** [comment]
Could you give the code in my PR a try?
