### ISSUE TITLE
Info how to use with UNIX filesystem sockets

### ISSUE THREAD

**Issue by tolgaulas** [pheanstalk/pheanstalk#233]
This is not a issue but recomendation for documentation; If you like to access beanstalkd over unix file sockets (Beanstalkd 1.12+), the static create fails. However the below works

```
$socket = new Pheanstalk\SocketFactory('unix:///tmp/beanstalkd.sock',-1,10,3);
$connection = new Pheanstalk\Connection($socket);
$pheanstalk = new Pheanstalk\Pheanstalk($connection);
```

assuming you started the beanstalkd with 
```
beanstalkd -l unix:/tmp/beanstalkd.sock
```

**Comment by SamMousa** [comment]
Feel free to submit a PR to improve docs!

**Comment by SamMousa** [comment]
I have implemented unix socket support for all socket implemenations in v5 (to be released). This means the workaround is no longer needed.
