### ISSUE TITLE
Migration to v4 notes

### ISSUE THREAD

**Issue by hayden-t** [pheanstalk/pheanstalk#234]
On main readme it didnt mention functions/procedures that have had changed params or return format.

Some ive found so far,

put() returns a job type object rather than job id, the job id is inside the object via getId()
statsJob(param1)  param1 is now job object rather than job id

**Comment by SamMousa** [comment]
> Pheanstalk 4.0 drops support for older PHP versions. It contains the following changes (among other things):
> - Strict PHP type hinting
> - Value objects for Job IDs
> - Functions without side effects
> - Dropped support for persistent connections
> - Add support for multiple socket implementations (streams extension, socket extension, fsockopen)

It seems pretty explicitly explained to me...
Also these errors will get caught both by static analysis as well as any integration tests...

**Comment by hayden-t** [comment]
Value objects for Job IDs - missed that meaning. 
thanks for your work, v4 now stays up compared with v3 that fatal crashed from timeout every minute
