### ISSUE TITLE
send/receive timeout of SocketSocket

### ISSUE THREAD

**Issue by dontub** [pheanstalk/pheanstalk#239]
As far as I can see there is only a connection timeout, but no send/receive timeout when using `SocketSocket`.

The initial timeouts fetched in https://github.com/pheanstalk/pheanstalk/blob/e4d0453ebbe9f8b176260f6a4eb57060f06ac130/src/Socket/SocketSocket.php#L38 and https://github.com/pheanstalk/pheanstalk/blob/e4d0453ebbe9f8b176260f6a4eb57060f06ac130/src/Socket/SocketSocket.php#L39 contain:
```
array(2) {
  'sec' =>
  int(0)
  'usec' =>
  int(0)
}
```

After the connection is established those timeouts are set again in https://github.com/pheanstalk/pheanstalk/blob/e4d0453ebbe9f8b176260f6a4eb57060f06ac130/src/Socket/SocketSocket.php#L56 and https://github.com/pheanstalk/pheanstalk/blob/e4d0453ebbe9f8b176260f6a4eb57060f06ac130/src/Socket/SocketSocket.php#L57

If the timeout is set to 0 send/receive operations never timeout (https://man7.org/linux/man-pages/man7/socket.7.html).

I think it should be possible to define send/receive timeout and if not defined a sensible default should be used, e.g. `ini_get('default_socket_timeout')`. WDYT?

**Comment by SamMousa** [comment]
Short, in case you want to start immediately:

Don't like changing the defaults. Do like making them configurable; this should be done via constructor arguments to the socket and the factory.

Will put a more detailed answer when time allows.

**Comment by SamMousa** [comment]
@dontub I have implemented this (and a lot of other things) in the v5 branch.

I've only exposed `connectTimeout` and `receiveTimeout` in the static factory (`Pheanstalk::create`) since not all implementations support `sendTimeout`. 
In case you need that you can create a `SocketFactory` manually.

**Comment by SamMousa** [comment]
Implemented in v5 (to be released).

**Comment by dontub** [comment]
Thanks!

**Comment by SamMousa** [comment]
If you have some time please give the alpha a go, it requires some changes in your code though
