### ISSUE TITLE
SocketSocket assumes first host address is the correct one

### ISSUE THREAD

**Issue by tchari** [pheanstalk/pheanstalk#240]
I've run into an issue that is related to how SocketSocket attempts to connect to beanstalkd.

In the SocketSocket constructor, we have the following code:
```
        $addresses = gethostbynamel($host);
        if ($addresses === false) {
            throw new ConnectionException(0, "Could not resolve hostname $host");
        }
        if (@socket_connect($this->socket, $addresses[0], $port) === false) {
            $error = socket_last_error($this->socket);
            throw new ConnectionException($error, socket_strerror($error));
        };
```
The issue is that gethostbyname returns a list of potential ip addresses. SocketSocket assumes the first one will work; but this may not be the case (and is not the case in my circumstances). However, SocketSocket does not attempt to connect to any other available addresses and just fails.

In my case, I'm using travis-ci. When travis spools up the VM, /etc/hosts looks like:
```
## Managed by Chef on packer-60def248-3389-4b9a-ace8-b6640fd62f86.c.eco-emissary-99515.internal :heart_eyes_cat:
## cookbook:: travis_build_environment
##     file:: templates/default/etc/cloud/templates/hosts.tmpl.erb

127.0.1.1 localhost localhost ip4-loopback

127.0.0.1 localhost nettuno travis vagrant travis-job-742fadd2-9f6d-4491-8bd1-b2b975f96acd
```

gethostbyname then the array ["127.0.1.1", "127.0.0.1"]. $addresses[0] is "127.0.1.1" and the connection is refused because beanstalkd is running on "127.0.0.1".

Does anyone have any advice on how to proceed? The only solution I can think of at the moment is to rewrite /etc/hosts during VM setup.

**Comment by SamMousa** [comment]
As far as I know clients are not required to try all ip addresses.
If I'm wrong we should change the implementation in the library.

Regarding your issue: just connect to beanstalk using a hardcoded IP.

**Comment by SamMousa** [comment]
Closing this, if the DNS is misconfigured then that's out of scope for this library.
Clients are not required to retry other addresses if records returned by DNS fail.
