### ISSUE TITLE
SocketSocket should silence calls to socket functions when handling failures

### ISSUE THREAD

**Issue by ktardif** [pheanstalk/pheanstalk#242]
This currently affects the v4 branch (last checked using v4.0.3).

Currently, `SocketSocket` silences the call to `socket_connect` via `@` in order to throw its own library-level exception (`ConnectionException`) on failure inside `__construct`. However, while calls to `socket_create`, `socket_write`, and `socket_read` also have code to throw library-level exceptions in a similar manner, they aren't silenced in the same manner. This results in an issue if an error handler is installed via `set_error_handler` which raises exceptions on warnings (in this case socket errors), since that results in library-level exceptions such as `SocketException` no longer being thrown as expected. An example which showcases this behavior:

```php
<?php

require_once __DIR__ . '/vendor/autoload.php';

set_error_handler(function ($severity, $message, $file, $line) {
    if (!(error_reporting() & $severity))
        return false;

    throw new ErrorException($message, 0, $severity, $file, $line);
});

$beanstalk = Pheanstalk\Pheanstalk::create('127.0.0.1');

while (true) {
    //if beanstalkd is shutdown or the connection is lost, socket_read will log a warning, resulting in:
    //Uncaught ErrorException: socket_read(): unable to read from socket [54]: Connection reset by peer
    //being thrown from the installed error handler

    //the expected exception is:
    //Uncaught Pheanstalk\Exception\SocketException: Connection reset by peer
    $job = $beanstalk->reserveWithTimeout(50);
}
```

I've included a PR #241 which fixes this.

**Comment by SamMousa** [comment]
Thanks, your PR has been merged. Sorry for the delay.

**Comment by ktardif** [comment]
No problem, thanks for merging it in!
