### ISSUE TITLE
Error: useTube(): Argument #1 ($tube) must be of type Pheanstalk\Values\TubeName, string given

### ISSUE THREAD

**Issue by reimax** [pheanstalk/pheanstalk#254]
code

```php
$pheanstalk = Pheanstalk::create('127.0.0.1);
        $pheanstalk
            ->useTube('test)
            ->put((string) json_encode($data));
```

i have error 
Pheanstalk\Pheanstalk::useTube(): Argument #1 ($tube) must be of type Pheanstalk\Values\TubeName, string given, called in .....

**Comment by alister** [comment]
Pheanstalk v5 has a lot of changes from older versions.  If you are using the latest version (with code that was written for older versions), there will be other updates required.
You can see an example of using a tube at https://github.com/pheanstalk/pheanstalk/blob/v5/tests/Integration/Examples/PublisherTest.php#L27

**Comment by reimax** [comment]
Then on the main page of the repository there are outdated examples. Where can I watch the current ones?

**Comment by SamMousa** [comment]
Hey @reimax, they have not yet been updated, feel free to make a PR though!
