### ISSUE TITLE
Can not delete empty job

### ISSUE THREAD

**Issue by nikozen** [pheanstalk/pheanstalk#266]
Hi,

**Test case :**

1. push a false job
```
  $out_queue =  \Pheanstalk\Pheanstalk::create("127.0.0.1");
  $out_queue->useTube( new \Pheanstalk\Values\TubeName ( "faketube" ) );
  $out_queue->put( false );
```

2. retrieve
```
  $in_queue =  \Pheanstalk\Pheanstalk::create("127.0.0.1");
  $in_queue->watch( new \Pheanstalk\Values\TubeName ( "faketube" ) );
```

  $job = $in_queue->reserveWithTimeout( 0 );        
  $in_queue->delete($job);

**Exception**
_PHP Fatal error:  Uncaught Pheanstalk\Exception\MalformedResponseException: Data length cannot be negative in /home/oseox/tool/src/3rdparty/vendor/pda/pheanstalk/src/Exception/MalformedResponseException.php:19_

**But Length is 0, not negative**

### Change

I made this change in file Connection.php

line 92
```
        // if ($dataLength <= 0) {
            if ($dataLength < 0) {
```

and line 96
```
            if ( $dataLength == 0 ) $data = '';
            else $data = $this->readData($socket, $dataLength);
```

It's not perfect, I still have exception, but I can delete the job at least

_PHP Fatal error:  Uncaught ValueError: "" is not a valid backing value for enum Pheanstalk\Values\ResponseType in /home/oseox/tool/src/3rdparty/vendor/pda/pheanstalk/src/Connection.php:87_

Would be great to handle this "job" nicely

PS: first time I open an issue, sorry it is inaccurate

**Comment by SamMousa** [comment]
It is a bug that jobs of length 0 cannot be reserved, can you make a PR?

Note that you should not be able to put false since false is not a string. Of course putting "" would give you the same bug.

**Comment by SamMousa** [comment]
Just line 92 should fix the issue. We still need to read 0 bytes so we can read the CRLF that follow them..

**Comment by nikozen** [comment]
Thank I check and PR asap...

false appear because I push lazily json_encode stuff 😅

**Comment by SamMousa** [comment]
Use JSON_THROW flag for json encode!
