### ISSUE TITLE
Delay any existing job.

### ISSUE THREAD

**Issue by sanjaymohnani** [pheanstalk/pheanstalk#76]
Is that possible to delay any existing job? As per my research, there's no any direct facility to delay any existing job.

I think, to delay any existing job, you need to delete previous one and add new one with delay information. But, in that case I'm unable to find actual tube name from which job was fetched. That also unable to get from reserve command response.

Correct me if I'm wrong.

Thank...

**Comment by hasidiluk** [comment]
@pda What happen when we execute `release` command job for the second time ?

**Comment by SamMousa** [comment]
@hasidiluk please do not necro threads and randomly ping people 5 years after a discussion.

You can find the beanstalk protocol specs here: https://github.com/beanstalkd/beanstalkd/blob/master/doc/protocol.txt
