### ISSUE TITLE
Socket error 13: Permission denied (connecting to localhost:11300) on CentOS 6.5 64bit

### ISSUE THREAD

**Issue by EricEric** [pheanstalk/pheanstalk#80]
I encounter the problem of Socket error 13: Permission denied (connecting to localhost:11300) on apache on centos 6.5, i dont know if this is a linux problem or not.

```
prod.ERROR: exception 'Pheanstalk_Exception_ConnectionException' with message 'Socket error 13: Permission denied (connecting to localhost:11300)' in /var/www/html/vendor/pda/pheanstalk/classes/Pheanstalk/Socket/NativeSocket.php:35
Stack trace:
#0 /var/www/html/vendor/pda/pheanstalk/classes/Pheanstalk/Connection.php(164): Pheanstalk_Socket_NativeSocket->__construct('localhost', 11300, 2)
#1 /var/www/html/vendor/pda/pheanstalk/classes/Pheanstalk/Connection.php(72): Pheanstalk_Connection->_getSocket()
#2 /var/www/html/vendor/pda/pheanstalk/classes/Pheanstalk/Pheanstalk.php(372): Pheanstalk_Connection->dispatchCommand(Object(Pheanstalk_Command_PutCommand))
#3 /var/www/html/vendor/pda/pheanstalk/classes/Pheanstalk/Pheanstalk.php(219): Pheanstalk_Pheanstalk->_dispatch(Object(Pheanstalk_Command_PutCommand))
```

**Comment by daonguyenvu** [comment]
Did you fix it? the same problem:
PHP Fatal error:  Uncaught exception 'Pheanstalk\\Exception\\ConnectionException' with message 'Socket error 13: Permission denied (connecting to x.x.x.x:11300)' in /var/www/html/beanstalkd/vendor/pda/pheanstalk/src/Socket/NativeSocket.php:40\nStack trace:\n#0 /var/www/html/beanstalkd/vendor/pda/pheanstalk/src/Connection.php(169): Pheanstalk\\Socket\\NativeSocket->__construct('x.x.x.x', 11300, 2)\n#1 /var/www/html/beanstalkd/vendor/pda/pheanstalk/src/Connection.php(77): Pheanstalk\\Connection->_getSocket()\n#2 /var/www/html/beanstalkd/vendor/pda/pheanstalk/src/Pheanstalk.php(384): Pheanstalk\\Connection->dispatchCommand(Object(Pheanstalk\\Command\\UseCommand))\n#3 /var/www/html/beanstalkd/vendor/pda/pheanstalk/src/Pheanstalk.php(335): Pheanstalk\\Pheanstalk->_dispatch(Object(Pheanstalk\\Command\\UseCommand))\n#4 /var/www/html/beanstalkd/index.php(14): Pheanstalk\\Pheanstalk->useTube('testtube')\n#5 {main}\n  thrown in /var/www/html/beanstalkd/vendor/pda/pheanstalk/src/Socket/NativeSocket.php on line 40

**Comment by lt** [comment]
For anyone else who stumbles on this issue, this is SELinux preventing the http user accessing the beanstalkd port.

Quick fix: `sudo semanage port -a -t http_port_t -p tcp 11300`

**Comment by Robdebert** [comment]
I have this problem on a virtual-machine running ubuntu server 16.04. Error-Message is 

`Warning: fsockopen(): unable to connect to localhost:11300 (Connection refused) in /var/www/phpci/vendor/pda/pheanstalk/src/Socket/StreamFunctions.php line 73`

What could i do here?
