### ISSUE TITLE
Connection refused

### ISSUE THREAD

**Issue by tim-peterson** [pheanstalk/pheanstalk#93]
Sorry for the noob question. Totally stuck. I just implemented the demo code exactly as specified and got the following error:

```
Fatal error: Uncaught exception 'Pheanstalk\Exception\ConnectionException' with message 'Socket error 61: Connection refused (connecting to 127.0.0.1:11300)' in /Applications/MNPP/Library/nginx/html/vendor/pda/pheanstalk/src/Socket/NativeSocket.php:40 Stack trace: #0 /Applications/MNPP/Library/nginx/html/vendor/pda/pheanstalk/src/Connection.php(169): Pheanstalk\Socket\NativeSocket->__construct('127.0.0.1', 11300, 2) #1 /Applications/MNPP/Library/nginx/html/vendor/pda/pheanstalk/src/Connection.php(77): Pheanstalk\Connection->_getSocket() #2 /Applications/MNPP/Library/nginx/html/vendor/pda/pheanstalk/src/Pheanstalk.php(384): Pheanstalk\Connection->dispatchCommand(Object(Pheanstalk\Command\UseCommand)) #3 /Applications/MNPP/Library/nginx/html/vendor/pda/pheanstalk/src/Pheanstalk.php(335): Pheanstalk\Pheanstalk->_dispatch(Object(Pheanstalk\Command\UseCommand)) #4 /Applications/MNPP/Library/nginx/html/application/controllers/blog.php(29): Pheanstalk\Pheanstalk->useTube('testtube') #5 [internal function]: Blog->beanstalk() #6 / in /Applications/MNPP/Library/nginx/html/vendor/pda/pheanstalk/src/Socket/NativeSocket.php on line 40
```

I'm using Pheanstalk version `2.*@dev`, PHP v.5.3.8, and Mac OSX Mavericks 10.9.4. I get the same exact error using `3.*@dev`.

Thoughts?

**Comment by pedroskakum** [comment]
I have the same problem:

running "telnet 127.0.0.1 11300", the ourput is:
Trying 127.0.0.1...
telnet: Unable to connect to remote host: Connection refused

but, running "ps auxw | grep beanstalkd", the output is:
pedro    21887  0.0  0.0  12800   964 pts/0    S+   17:10   0:00 grep beanstalkd

i`m using framawork laravel 5.4 with composer package "pda/pheanstalk": "^3.1" and OS Deepin 15.4 (linux)

**Comment by pda** [comment]
```
pedro 21887 0.0 0.0 12800 964 pts/0 S+ 17:10 0:00 grep beanstalkd
```
Looks like beanstalkd was not running — your `ps … | grep beanstalkd` command was only seeing its own `grep beanstalkd` process.
